name: Analyser CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Lint with Ruff
        run: |
          ruff check

      - name: Format with Black
        run: |
          black --check .

      - name: Sort imports with Isort
        run: |
          isort --check-only .

      - name: Static type checking with Mypy
        run: |
          mypy ./src/log_analyser.py
