name: Analyser CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Lint with Ruff
        run: |
          ruff check

      - name: Format with Black
        run: |
          black --check .

      - name: Sort imports with Isort
        run: |
          isort --check-only .

      - name: Static type checking with Mypy
        run: |
          mypy ./src/log_analyser.py

  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run unittests
        run: |
          tree
          pwd
          cd tests
          cat ../config/log_analyser.json
          python -m unittest tests/test_log_analyser.py
    

  Analysing-log:
    runs-on: ubuntu-latest
    needs: [Run-tests]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run LogAnalyser
        run: |
          python src/log_analyser.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: analyse-results
          path: ./reports
